Regex is better at validating URLs; can also post gifs :)
mrios730/Team-25 pull request #27
Opened 2019-03-13 13:32 UTC by jhuang09

2019-03-13 14:32 UTC, dhgarrette requested changes
Nice!  Since this regex is more complicated than the previous one, can you add a comment directly above it that explains what kinds of patterns it captures?

2019-03-14 01:13 UTC, jhuang09 commented
I've added a comment explaining its pattern. It seems a bit complicated and I'm not sure if it can be made clearer. Thoughts?

2019-03-14 03:32 UTC, dhgarrette commented on src/main/java/com/google/codeu/servlets/MessageServlet.java
> +    /**
I think it's pretty good, but I have two comments:
1) "Javadoc" style comments `/**  */` are for documenting methods and classes, but regular comments should use `//`.
2) I think you might be able to simplify slightly by giving a real example, and a little bit of prose description.  Maybe something like:

```
// Matches the URL of an image file, with an optional caption. For example:
//     [the google logo] http://www.google.com/images/logo.png
// Matched URLs must end with one of: .png, .jpg, .gif
String regex = "(\\[.+\\])?\\s(https?://[\\S+\\.]+/([\\S+\\.?]+/?)+\\.(png|jpg|gif))";

// Replaces the URL with the actual image. If a caption was given, it is printed below the image.
String replacement = "<figure><img src=\"$2\" /> <figcaption>$1</figcaption></figure>";
```

2019-03-15 21:01 UTC, dhgarrette approved these changes
Thanks, Janny!

2019-03-15 21:09 UTC, jhuang09 commented
I've updated the comments, but I realized that there's some faulty logic with my regex that I will fix soon! Will update once I get a better regex

2019-03-16 02:44 UTC, dhgarrette commented
I merged my PR with the unit test, so you can update that as needed to add test cases for your change.

2019-03-19 14:58 UTC, merged